backend:
  name: git-gateway
  branch: master

media_folder: "static/images/uploads"
public_folder: "images"

collections:
  - name: "product" # Used in routes, e.g., /admin/collections/product
    label: "Sản phẩm" # Used in the UI
    folder: "content/product" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents
    slug: "{{year}}-{{month}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Tên sản phẩm", name: "name", widget: "string"}
      - {label: "Hình ảnh", name: "thumbnail", widget: "image"}
      - {label: "Giá gốc", name: "originPrice", widget: "number"}
      - {label: "Giá giảm", name: "discountPrice", widget: "number"}